name    'puppet-redmine-nginx'
version '0.0.1'
source  'git://github.com/samrose/puppet-redmine-nginx.git'
author  'Uwe Kleinmann, Sam Rose'
license 'BSD'
summary 'Puppet Redmine Module with nginx vhost'
description 'Puppet Redmine Module with nginx vhost'
project_page 'https://github.com/samrose/puppet-redmine-nginx.git'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
dependency 'puppetlabs/mysql', '>= 0.5.0'
